lang: "zh-CN"
title: "CQ备忘录"
description: "Blog posts, presentations, podcasts, and other things..."
permalink: /:title/
timezone: Asia/Shanghai
theme: jekyll-theme-hacker
google_analytics: UA-172803163-1
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag