lang: "zh-CN"
title: "CQ备忘录"
description: "一间存放故事的仓库"
logo: /static/chenqi.jpg
author: ChenQi
permalink: /:title/
timezone: Asia/Shanghai
theme: jekyll-theme-hacker
google_analytics: UA-172803163-1
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag