lang: "zh-CN"
title: "CQ备忘录"
description: "一间存放故事的仓库"
logo: /static/chenqi.jpg
author: ChenQi
permalink: /:title/
timezone: Asia/Shanghai
remote_theme: 9468305/hacker
google_analytics_4: G-WY4HPW1HYT
plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
social:
  name: ChenQi
  links:
    - https://www.linkedin.com/in/chenqi-app/
    - https://github.com/9468305